module.exports = {
  name: 'Rehash Trash',
  slug: 'rehash-trash',
  logo: 'images/rehash-trash/logo.jpg',
  stories: [
    {
      title: 'Hello Name 1',
      content: 'This is some content for the ting',
      image: 'images/rehash-trash/1.jpg',
      ctaText: 'Buy Now',
      ctaColor: '#fc0',
      ctaTextColor: '#fff',
      ctaLink: 'https://alink.com',
      contentColor: 'rgb(255, 204, 0)',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
    {
      title: 'Buy a nut',
      content: 'This is some content for the ting',
      image: 'images/rehash-trash/2.jpg',
      contentColor: '#fff',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#ccc',
    },
    {
      title: 'Instagram like GIF',
      content: "",
      image: 'https://media.giphy.com/media/U7baL14QNZ0u3ITmiO/giphy.gif',
      contentColor: '#fff',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
    {
      title: 'But we can sell stuff on it',
      content: "Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.",
      image: 'https://media.giphy.com/media/U7baL14QNZ0u3ITmiO/giphy.gif',
      contentColor: '#fff',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
    {
      title: 'Instagram',
      content: "Go ahead, swipe up and buy it",
      image: 'https://media.giphy.com/media/U7baL14QNZ0u3ITmiO/giphy.gif',
      ctaText: 'Buy Now',
      ctaColor: '#333',
      ctaTextColor: '#fff',
      ctaLink: 'https://alink.com',
      contentColor: '#fff',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
  ],
};
