export default {
  brand: 'rehash-trash',
  name: 'our-story',
  title: 'Our Story',
  h2: 'Rehash Trash: Recycling Rubbish, Renewing Lives',
  slug: 'our-story',
  image: 'images/rehash-trash/2.jpeg',
  ctaText: 'Learn More',
  ctaLink: 'checkout',
  stories: [
    {
      image: 'images/rehash-trash/2.jpeg',
      blur: '2px',
    },
    {
      content: 'Rehash Trash is a female empowerment, skills-training and environmental clean-up initiative all in one. Through upcycling solutions to Cambodia’s plastic pollution, we employ marginalised Khmer women to create products of value, so they can support their families and transform their lives.',
      image: 'images/rehash-trash/ourstory-1.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Our products are 100% upcycled from discarded materials rescued from the environment. Rehash Trash is creating sustainable and fair-trade employment opportunities for our women, and ethical shopping with real social and eco impact for you.',
      image: 'images/rehash-trash/ourstory-2.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Rehash Trash is a social enterprise from the Green Gecko Project, a Cambodian NGO working with former street kids. It was developed to focus on the mothers of those children, creating long-term solutions for the families and enabling the kids to stay in full-time education.',
      image: 'images/rehash-trash/ourstory-3.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Our women were from uneducated and often abusive backgrounds; some also suffered from disabilities or addictions. They had never before had the opportunity of a job that was neither degrading or dangerous.',
      image: 'images/rehash-trash/ourstory-4.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Rehash Trash teaches them new skills and provides a decent income in a safe, happy and stable work environment. Rehash Trash: empowering women through sustainable employment while also cleaning up the environment by turning trash into treasure!',
      image: 'images/rehash-trash/ourstory-5.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
  ],
};
