export default {
  brand: 'rehash-trash',
  name: 'recycling-rubbish',
  title: 'Recycling Rubbish',
  h2: 'Recycling Rubbish: Environment + Community',
  slug: 'recycling-rubbish',
  image: 'images/rehash-trash/recycling-rubbish-1.jpeg',
  ctaText: 'Learn More',
  ctaLink: 'checkout',
  stories: [
    {
      image: 'images/rehash-trash/recycling-rubbish-1.jpeg',
      blur: '2px',
    },
    {
      content: 'Our products are made from 100% upcycled materials. Sadly, in Siem Reap, these materials are abundant - discarded plastic trash litters the streets and fields. Our team of collectors help clean up the environment by rescuing some of that rubbish. ',
      image: 'images/rehash-trash/recycling-rubbish-2.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'They bring it to our workshop, where it is washed thoroughly, dried and prepared for upcycling. We rescue literally thousands of items of plastic trash each week, preventing them from going into landfill or waterways. ',
      image: 'images/rehash-trash/recycling-rubbish-3.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'We do not dye the materials because we don’t want to add un-necessary pollutants into the environment. However in Cambodia, plastic comes in a vibrant array of colours, which means we offer a rainbow range in our products.',
      image: 'images/rehash-trash/recycling-rubbish-4.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'We often welcome local school children and students to our recycling workshops. This gives us the opportunity to discuss the dangers of single-use plastic in a fun and engaging way, helping to inspire the next generation of Cambodian eco-warriors!',
      image: 'images/rehash-trash/recycling-rubbish-5.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'All our women have received Plastic Free Cambodia workshops on how to avoid single-use plastic and together are proudly keeping our workshop a plastic-free zone by bringing re-usable containers for their food and drink. ',
      image: 'images/rehash-trash/recycling-rubbish-6.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Both Rehash Trash and  Green Gecko regularly take part in city clean-up initiatives to minimise waste. We are proud to collaborate in raising awareness of the plastic issues in our region with community eco partners Refill Not Landfill, Plastic Free Cambodia, Naga Earth and Cleanbodia.',
      image: 'images/rehash-trash/recycling-rubbish-7.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
  ],
};
