export default {
  name: 'recycling',
  title: 'Recycling Trash: Recycling Rubbish, Renewing Lives',
  slug: 'recycling',
  // image: 'images/rehash-trash/1.jpg',
  stories: [
    {
      title: 'About me',
      content: 'This is some content for the ting',
      // image: 'images/rehash-trash/1.jpg',
      ctaLink: 'https://alink.com',
      contentColor: 'rgb(255, 204, 0)',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
    {
      title: 'Tell Me',
      content: 'This is some content for the ting',
      image: 'images/rehash-trash/1.jpg',
      ctaLink: 'https://alink.com',
      contentColor: 'rgb(255, 204, 0)',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
    {
      title: 'Will we nest further?',
      content: 'This is some content for the ting',
      image: 'images/rehash-trash/1.jpg',
      ctaLink: 'https://alink.com',
      contentColor: 'rgb(255, 204, 0)',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
    {
      title: 'Hello Name 1',
      content: 'This is some content for the ting',
      image: 'images/rehash-trash/1.jpg',
      ctaLink: 'https://alink.com',
      contentColor: 'rgb(255, 204, 0)',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
    {
      title: 'Hello Name 2',
      content: 'This is some content for the ting',
      image: 'images/rehash-trash/1.jpg',
      ctaLink: 'https://alink.com',
      contentColor: 'rgb(255, 204, 0)',
      contentBackgroundColor: 'rgba(0, 0, 0, 0.8)',
      backgroundColor: '#333',
    },
  ],
};
