export default {
  name: 'renewing-lives',
  title: 'Renewing Lives',
  h2: 'Renewing Lives: Female Empowerment',
  slug: 'renewing-lives',
  image: 'images/rehash-trash/renewing-lives-1.jpeg',
  ctaText: 'Learn More',
  ctaLink: 'renewing-lives',
  stories: [
    {
      image: 'images/rehash-trash/renewing-lives-1.jpeg',
      blur: '2px',
    },
    {
      content: 'Rehash Trash began as a morning workshop in 2015, where the women quickly mastered their new production skills.  They also had to learn how to work as a team, appropriate work-place conduct, and other employment skills that many of us simply take for granted. ',
      image: 'images/rehash-trash/renewing-lives-2.jpeg',
      blur: '2px',
      ctaText: 'Show Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'In 2017, with the women’s work ethic going through the roof, we opened our very own store in Siem Reap. This furthered their empowerment by crucially creating full-time employment, and seeing their products being sold to visitors from all over the world.',
      image: 'images/rehash-trash/renewing-lives-3.jpeg',
      blur: '2px',
      ctaText: 'Show Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Our women gain not only a significant economic stability at Rehash Trash, but by working with their hands to make these unique products, also experience a creative, therapeutic benefit. They are rightly very proud of the pieces they create!',
      image: 'images/rehash-trash/renewing-lives-4.jpeg',
      blur: '2px',
      ctaText: 'Show Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Our women teach their skills in daily recycling workshops to local and international visitors alike, which is hugely empowering for them and a lot of fun for you. They receive ongoing spoken English classes, which they love practicing when you visit.',
      image: 'images/rehash-trash/renewing-lives-5.jpeg',
      blur: '2px',
      ctaText: 'Show Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'We offer a comprehensive approach to our women’s well-being and personal development. As well as supported access to medical and reproductive heathcare, our women also benefit from a whole host of additional  holistic services. (link to Donate Now)',
      image: 'images/rehash-trash/renewing-lives-6.jpeg',
      blur: '2px',
      ctaText: 'Show Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'We want our women to feel true ownership of Rehash Trash and share a collaborative approach to ideas. They are involved in every aspect: from the design, creation and promotion of our products; to spreading a strong environmental message to our community and visitors.',
      image: 'images/rehash-trash/renewing-lives-7.jpeg',
      blur: '2px',
      ctaText: 'Show Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
  ],
};
