export default {
  name: 'workshops',
  title: 'Workshops',
  h2: 'Workshops',
  slug: 'workshops',
  image: 'images/rehash-trash/workshops-1.jpeg',
  ctaText: 'Learn More',
  ctaLink: 'workshops',
  stories: [
    {
      image: 'images/rehash-trash/workshops-1.jpeg',
      blur: '2px',
    },
    {
      content: 'Our recycling workshops offer a fun activity in Siem Reap. Our wonder-women will teach you how to crochet your own piece of Rehash Trash which you keep as a souvenir. Take part in the knowledge growth of our local community, pick up some Khmer vocabulary and leave with new friends!',
      image: 'images/rehash-trash/workshops-2.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: ' Crochet workshops (max. 15 people)\n\n$8/pax: friendship band, keyring or coaster (up to 2 hours)\n$16/pax: can holder, small tablemat or basket (up to 4 hours) \n$30/pax: larger basket or set (up to 8 hours)',
      image: 'images/rehash-trash/workshops-3.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Crochet/Washing workshops (max. 30 people)\n\nDouble your impact by assisting our lovely washing  team before you try your hand at crochet! Bring some of your own bags from home, and see them go through the Rehash Trash process:\n\n$12/pax: 1 hour washing, 1 hour crochet',
      image: 'images/rehash-trash/workshops-4.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
    {
      content: 'Workshops are available every day from 8am – 5pm; \nfor groups of 4 or more, book in advance by emailing workshops@rehashtrash.org',
      image: 'images/rehash-trash/workshops-5.jpeg',
      blur: '2px',
      ctaText: 'Shop Now',
      ctaLink: '/rehash-trash/shop',
      type: 'story-card',
    },
  ],
};
